### PR TITLE
Remove repetition

### PR DESCRIPTION
**Pull request by anxolin**
Reply to comment https://github.com/gnosis/dex-swap/pull/8/files#r516041465

### CODE REVIEW

**Comment by biocom** [comment]
Thanks for the suggestion Anxo. For me I was hoping to have it in a variable as I see it going to be used in other components too. IMO your solution makes the background element dryer in this particular instance, but doesn't take into account further usage of it else where and we still repeat the repeat of &:hover &:focus etc. makes it less dry again... Otherwise your call here.

**Comment by biocom** [comment]
Thanks for the suggestion Anxo. For me I was hoping to have it in a variable as I see it going to be used in other components too. IMO your solution makes the background element dryer in this particular instance, but doesn't take into account further usage of it else where and we still repeat the repeat of &:hover &:focus etc. makes it less dry again... Otherwise your call here.

**Review by Velenir — APPROVED** [review]

**Comment by anxolin** [comment]
Yes, in fact, I'm working in a new PR to make a second and drier alternative, will create soon

**Comment by Velenir** [comment]
If you want avariable
```ts
const complexMixin = css`
  background-color: ${({ theme }) => `linear-gradient(270deg, ${theme.purple} 30%, ${theme.blue1} 70%);`};
`
```
Or were you thinking about a css variable

**Comment by biocom** [comment]
@Velenir Was thinking about a variable (const) like in your example. But got errors when I added it. I think I missed the ..css` prefix which is required in TypeScript?

**Comment by Velenir** [comment]
> @Velenir Was thinking about a variable (const) like in your example. But got errors when I added it. I think I missed the ..css` prefix which is required in TypeScript?

It's not that `css` is needed for TS, it's for styled-components interpolation of template functions
https://styled-components.com/docs/api#css

**Comment by anxolin** [comment]
This was superseded by #22

**Pull request closed without merging**
